export const LOAD_INITIAL_TREE = 'LOAD_INITIAL_TREE';
export const FETCH_TREE_FAILED = 'FETCH_TREE_FAILED';
export const LOAD_DROPPED_TREE = 'LOAD_DROPPED_TREE';
export const EXPAND_NODE = 'EXPAND_NODE';
export const CLOSE_NODE = 'CLOSE_NODE';
export const EDIT_NODE = 'EDIT_NODE';
export const SET_ROUTE_PARAMS = 'SET_ROUTE_PARAMS';